name: "FAP: Daily Build Release"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    name: "Build Flipper App"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: release

      - name: Rename FAP
        run: |
          mkdir release
          DATE=$(date +'%Y-%m-%d')
          for f in ${{ steps.build-app.outputs.fap-artifacts }}/*.fap; do
            cp "$f" "release/myapp-$DATE.fap"
          done

      - name: Delete old daily release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Daily Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: daily
          name: Daily Build
          body: |
            Automatically generated Flipper Zero app build.
            Updated: ${{ github.event.head_commit.timestamp }}
          files: release/*.fap
